//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Музыкальный_магазин_пластинок
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пластинки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пластинки()
        {
            this.Продажи = new HashSet<Продажи>();
        }
    
        public int Id { get; set; }
        public string Название { get; set; }
        public Nullable<int> Год_издания { get; set; }
        public Nullable<int> Количество_треков { get; set; }
        public Nullable<decimal> Себестоимость { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<int> Скидка { get; set; }
        public Nullable<int> ID_зарезервировавшего { get; set; }
        public Nullable<int> Испольнитель_ID { get; set; }
        public Nullable<int> Издатель_ID { get; set; }
        public Nullable<int> Жанр_ID { get; set; }
        public Nullable<int> Количество { get; set; }
        public string Обложка { get; set; }
        public Nullable<int> Количество_зарезервировано { get; set; }
    
        public virtual Жанры Жанры { get; set; }
        public virtual Издатели Издатели { get; set; }
        public virtual Исполнители Исполнители { get; set; }
        public virtual Покупатели Покупатели { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажи> Продажи { get; set; }
    }
}
